app/__init__.py
from flask import Flask, render_template
from flask.ext.bootstrap import Bootstrap
import eventlet
from flask.ext.socketio import SocketIO
from flask_restful import Api
import logging
from logging.handlers import RotatingFileHandler
from flask.ext.compress import Compress

eventlet.monkey_patch()

app = Flask(__name__)
app.config.from_object('config.default')
app.config.from_pyfile('instance/config.py', silent=True)
#app.config.from_envvar('APP_CONFIG_FILE')

Compress(app)
bootstrap = Bootstrap(app)
socketio = SocketIO(app)
api = Api(app)

handler = RotatingFileHandler(
    app.config['LOGGING_LOCATION'],
    maxBytes=1024 * 1024 * 10,
    backupCount=2
    )
handler.setLevel(app.config['LOGGING_LEVEL'])
formatter = logging.Formatter(app.config['LOGGING_FORMAT'])
handler.setFormatter(formatter)
app.logger.addHandler(handler)

app_list = app.config['APP_LIST']
report_dir = app.config['PPE_REPORT_PATH']
script_path = app.config['PPE_SCRIPT_PATH']

@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404

@app.route('/')
def index():
    return render_template('index.html')

from app.report.views import report as report_module

app.register_blueprint(report_module)

app/report/views.py
#coding:utf-8
from flask import Blueprint, render_template, request, make_response, redirect, abort, url_for
import os
from RunForm import *
from OpenForm import *
from task import start_command_task, emit_message
from flask_restful import Resource
from app import api, app, app_list, report_dir, script_path

report = Blueprint('report', __name__, url_prefix='/report')

@report.route('/')
def index():
    run_form = RunForm()
    open_form = OpenForm()
    html_report_list = get_file_list_by_ext(report_dir, '.html')
    report_list = list(set(map(lambda x: os.path.dirname(x), html_report_list)))
    debug_report_list = get_file_list_by_ext(report_dir, '.debug')
    return render_template('report/index.html', report_list = report_list, debug_report_list = debug_report_list, run_form = run_form, open_form = open_form)

@report.route('/show/')
def show():
    report_path = request.args.get('name', '')
    full_report_path = get_full_report_path(report_dir, report_path)
    report_object = None
    try:
        report_object = open(full_report_path)
        content = report_object.read()
    except IOError as e:
        app.logger.error(e)
        return render_template('report/output.html', result = e)
    finally:
        if report_object is not None:
            report_object.close()
    response = make_response(content)
    if str(report).endswith('.debug'):
        response.mimetype = "text/plain;charset=utf-8"
    return response

@report.route('/show/<log>')
def show_log(log):
    if str(log).startswith('log.html'):
        return redirect(str(request.referrer).replace('report.html', 'log.html'))
    else:
        return abort(404)

@report.route('/run/', methods=['POST'])
def run():
    form = RunForm()
    if form.validate_on_submit():
        app_name = form.app.data
        result = run_test(script_path, app_name)
    else:
        result = form.app.errors
    emit_message(result)
    app.logger.debug(result)
    return render_template('report/output.html', result = result)

@report.route('/open/', methods=['POST'])
def open_report():
    form = OpenForm()
    if form.validate_on_submit():
        report_path = form.path.data
        full_report_path = get_full_report_path(report_dir, report_path)
        if os.path.isfile(full_report_path):
            return redirect(url_for('report.show', name = report_path))
        else:
            result = "can not find %s" % (full_report_path)
    else:
        result = form.path.errors
    app.logger.debug(result)
    return render_template('report/output.html', result = result)

def step((ext, file_list), dirname, names):
    ext = ext.lower()
    for name in names:
        if name.lower().endswith(ext):
            file_list.append(os.path.join(dirname, name))

def get_file_list_by_ext(top_dir, ext):
    file_list = []
    os.path.walk(top_dir, step, (ext, file_list))
    result_list = list(set(map(lambda x: x[len(top_dir):], file_list)))
    return result_list

def get_full_report_path(report_dir, report_path):
    if report_path.startswith(os.sep):
        full_report_path = report_dir + report_path
    else:
        full_report_path = os.path.join(report_dir, report_path)
    return full_report_path

def run_test(script_path, app_name):
    if os.path.isfile(script_path):
        start_command_task([ "python", "-u", script_path, app_name ])
        result = 'Process Started'
    else:
        result = "no file of %s" % (script_path)
    return result

#curl -X POST http://0.0.0.0:5050/report/run/aaa
class RunTest(Resource):
    def post(self, app_name):
        if app_name in app_list:
            result = run_test(script_path, app_name)
        else:
            result = app_name + ' is not in valid app list.'
        app.logger.debug(result)
        return {'status': result}, 201

api.add_resource(RunTest, '/report/run/<string:app_name>')

@report.route('/start/')
def start():
    start_command_task([ "python", "-u", '/Users/liugeorge/workspace/reporter/app/report/slow.py' ])
    return render_template('report/output.html')

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block head %}
    {{ super() }}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static',filename = 'favicon.png') }}" type='image/x-icon'/>
    <link rel="icon" href="{{ url_for('static',filename = 'favicon.png') }}" type="image/x-icon"/>
    {#<script type=text/javascript src="{{ url_for('static', filename='jquery-1.12.0.min.js') }}"></script>
    <script type=text/javascript src="{{ url_for('static', filename='socket.io.js') }}"></script>#}
    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js"></script>
{% endblock %}

{% block title %}Home{% endblock %}

{% block navbar %}
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Home</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/report">Report</a></li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        {% block page_content %}{% endblock %}
        <hr>
        <div class="row">
            <div class="col-md-12">
                <footer>
                    <p>&copy; Copyright 2016 Dianping</p>
                </footer>
            </div>
        </div>
    </div>

    {% block scripts %}
        {{ super() }}
    {% endblock %}

{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Reporter System{% endblock %}

{% block page_content %}
    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron">
                <h1>Reporting Tool</h1>
                <p>The web to view the online reports ...</p>
                <p><a class="btn btn-primary btn-lg" href="/report" role="button">Click it</a></p>
            </div>
        </div>
    </div>

{% endblock %}

app/templates/report/index.html
{% extends "base.html" %}

{% block title %}Report Portal{% endblock %}

{% block head %}
    {{ super() }}
    <script type="text/javascript" charset="utf-8">
        $(document).ready(function () {
            (function ($) {
                $('#filter').keyup(function () {
                    var rex = new RegExp($(this).val(), 'i');
                    $('.searchable div').hide();
                    $('.searchable div').filter(function () {
                        return rex.test($(this).attr('id'));
                    }).show();
                })
            }(jQuery));
        });
    </script>
{% endblock %}

{% block page_content %}
    <h1>Report Portal</h1>

    <div class="panel panel-default">
        <div class="panel-heading">Run Test Group</div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-3">
                    <form class="form-inline" method="POST" action="{{ url_for('report.run') }}">
                        <div class="form-group">
                            <label class="sr-only" for="app">Run app on the server</label>
                            <div class="input-group">
                                {{ run_form.hidden_tag() }}
                                {{ run_form.app(class_="form-control") }}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Run</button>
                    </form>
                    <small class="text-muted">
                        Select a test group and click Run button to run.
                    </small>
                </div>
                <div class="col-md-9">
                    Or Use Curl, <code>curl -X POST http://&lt;host&gt;:5050/report/run/&lt;test_group&gt;</code></br>
                    Output: <code>{"status": "Process Started"}</code>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="input-group"><span class="input-group-addon">Report Filter</span>
                <input id="filter" type="text" class="form-control" placeholder="Type report name here...">
            </div>
        </div>
        <div class="col-md-6">
            <form class="form-inline" method="POST" action="{{ url_for('report.open_report') }}">
                <div class="form-group">
                    <label class="sr-only" for="path">Open report on the server</label>
                    <div class="input-group"><span class="input-group-addon">Open Report</span>
                        {{ open_form.hidden_tag() }}
                        {{ open_form.path(size=50, id='open_report', class_="form-control", placeholder="The report path '/report-arts-it-index-tests/report.html'") }}
                    </div>
                </div>
                <button type="submit" class="btn btn-default">Open</button>
            </form>
        </div>
    </div>
    <hr>

    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">Html Reports <span class="badge">{{ report_list|length }}</span></div>
                <div class="panel-body">
                    <ul class="list-group searchable">
                        {% for report in report_list %}
                            <div id="{{ report }}">
                                {% if 'fail' in report %}
                                    <li class="list-group-item list-group-item-danger">{{ report }}</li>
                                {% else %}
                                    <li class="list-group-item list-group-item-success">{{ report }}</li>
                                {% endif %}
                                <a id="link" class="btn btn-default btn-link"
                                   href="{{ url_for('report.show', name=report + '/report.html') }}"
                                   role="button">Report</a>
                                <a id="link" class="btn btn-default btn-link"
                                   href="{{ url_for('report.show', name=report + '/log.html') }}"
                                   role="button">Log</a>
                                </li>
                            </div>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">Debug Reports <span class="badge">{{ debug_report_list|length }}</span></div>
                <div class="panel-body">
                    <ul class="list-group searchable">
                        {% for debug in debug_report_list %}
                            <div id="{{ debug }}">
                                {% if 'fail' in debug %}
                                    <li class="list-group-item list-group-item-danger">{{ debug }}</li>
                                {% else %}
                                    <li class="list-group-item list-group-item-success">{{ debug }}</li>
                                {% endif %}
                                <a id="link" class="btn btn-default btn-link"
                                   href="{{ url_for('report.show', name=debug) }}"
                                   role="button">Debug</a>
                                </li>
                            </div>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(".searchable a").hover(
                function () {
                    var report_url = decodeURIComponent($(this).attr('href'))
                    $('#open_report').val(report_url.split('=')[1])
                }
        );
    </script>
{% endblock %}

app/templates/report/output.html
{% extends "base.html" %}

{% block title %}Report Portal{% endblock %}

{% block head %}
    {{ super() }}
    <script type="text/javascript" charset="utf-8">
        $(document).ready(function () {
            namespace = '/test'; // change to an empty string to use the global namespace

            // the socket.io documentation recommends sending an explicit package upon connection
            // this is specially important when using the global namespace
            var socket = io.connect('http://' + document.domain + ':' + location.port + namespace);

            // event handler for server sent data
            // the data is displayed in the "Received" section of the page
            socket.on('my response', function (msg) {
                $('#output').append('<br>' + $('<div/>').text(msg.data).html());
            });
        });
    </script>
{% endblock %}

{% block page_content %}
    <h1>Report Portal</h1>
    <div class="alert alert-info" role="alert">{{ result }}</div>
    <div id="output"></div>
{% endblock %}